//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.20 at 03:23:31 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://advantage.store/shipex/service", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package store.advantage.shipex.service;
