version: '3'
services:
  configservice:
    image: advantageonlineshopping/aos-configservice:aos-spring-deployment
    ports:
      - "${CONFIG_SERVICE_PORT}:8888"
    container_name: aos_config_service
    restart: always
    volumes:
      - data-volume-config-service:/config-repo
  postgresql:
    image: advantageonlineshopping/aos-postgres
    ports:
      - "${POSTGRES_PORT}:5432"
    container_name: postgresql
    restart: always
    volumes:
      - data-volume-postgres:/var/lib/postgresql/data
  tomcat_6:
    env_file:
      - .env
      - .env_private
    image: advantageonlineshopping/aos-main-app
    ports:
      - "${MAIN_PORT}:8080"
    depends_on:
      - "postgresql"
    container_name: tomcat_6
    restart: always
  tomcat_account:
    env_file:
      - .env
      - .env_private
    image: advantageonlineshopping/aos-accountservice:aos-spring-deployment
    ports:
      - "${ACCOUNT_PORT}:8080"
    depends_on:
      - "postgresql"
    container_name: aos_account
    restart: always
    environment:
      - SPRING_CLOUD_CONFIG_URI=http://configservice:${CONFIG_SERVICE_PORT}
      - SPRING_PROFILES_ACTIVE=docker
volumes:
  data-volume-postgres:
  data-volume-config-service:
