version: '3.2'
services:
  config-service:
    image: advantageonlineshopping/aos-configservice-dev:aos_config_deployment
    ports:
      - "8888:8888"
    container_name: aos_config_service
    restart: always
    environment:
      - CONFIG_REPO_FILE_SYSTEM=file:///configservice/microservices
      - CONFIG_SERVICE_ACTIVE_PROFILE=native
    volumes:
      - type: bind
        source: data-volume-config-service
        target: /configservice/microservices
  postgresql:
    image: advantageonlineshopping/aos-postgres-dev
    ports:
      - "${POSTGRES_PORT}:5432"
    container_name: postgresql
    restart: always
  tomcat_6:
    env_file:
      - .env
      - .env_private
    image: advantageonlineshopping/aos-main-app
    ports:
      - "${MAIN_PORT}:8080"
    depends_on:
      - "postgresql"
    container_name: tomcat_6
    restart: always
  tomcat_account:
    env_file:
      - .env
      - .env_private
    image: advantageonlineshopping/aos-accountservice-dev:aos_config_deployment
    ports:
      - "${ACCOUNT_PORT}:8080"
    depends_on:
      - "postgresql"
      - "config-service"
    container_name: aos_account
    restart: always
    environment:
      - CONFIG_SERVICE_URI=http://config-service:8888
      - ACTIVE_PROFILE=dev
volumes:
  data-volume-config-service:
