
package accountservice.store.online.advantage.com;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebService(name = "AccountServicePort", targetNamespace = "com.advantage.online.store.accountservice")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
        ObjectFactory.class
})
public interface AccountServicePort {


    /**
     * @param getAccountByIdRequest
     * @return returns accountservice.store.online.advantage.com.GetAccountByIdResponse
     */
    @WebMethod(operationName = "GetAccountById")
    @WebResult(name = "GetAccountByIdResponse", targetNamespace = "com.advantage.online.store.accountservice", partName = "GetAccountByIdResponse")
    public GetAccountByIdResponse getAccountById(
            @WebParam(name = "GetAccountByIdRequest", targetNamespace = "com.advantage.online.store.accountservice", partName = "GetAccountByIdRequest")
                    GetAccountByIdRequest getAccountByIdRequest);

    /**
     * @param getAccountPaymentPreferencesRequest
     * @return returns accountservice.store.online.advantage.com.GetAccountPaymentPreferencesResponse
     */
    @WebMethod(operationName = "GetAccountPaymentPreferences")
    @WebResult(name = "GetAccountPaymentPreferencesResponse", targetNamespace = "com.advantage.online.store.accountservice", partName = "GetAccountPaymentPreferencesResponse")
    public GetAccountPaymentPreferencesResponse getAccountPaymentPreferences(
            @WebParam(name = "GetAccountPaymentPreferencesRequest", targetNamespace = "com.advantage.online.store.accountservice", partName = "GetAccountPaymentPreferencesRequest")
                    GetAccountPaymentPreferencesRequest getAccountPaymentPreferencesRequest);

    /**
     * @param accountDeleteRequest
     * @return returns accountservice.store.online.advantage.com.AccountDeleteResponse
     */
    @WebMethod(operationName = "AccountDelete")
    @WebResult(name = "AccountDeleteResponse", targetNamespace = "com.advantage.online.store.accountservice", partName = "AccountDeleteResponse")
    public AccountDeleteResponse accountDelete(
            @WebParam(name = "AccountDeleteRequest", targetNamespace = "com.advantage.online.store.accountservice", partName = "AccountDeleteRequest")
                    AccountDeleteRequest accountDeleteRequest);

    /**
     * @param getAllAccountsRequest
     * @return returns accountservice.store.online.advantage.com.GetAllAccountsResponse
     */
    @WebMethod(operationName = "GetAllAccounts")
    @WebResult(name = "GetAllAccountsResponse", targetNamespace = "com.advantage.online.store.accountservice", partName = "GetAllAccountsResponse")
    public GetAllAccountsResponse getAllAccounts(
            @WebParam(name = "GetAllAccountsRequest", targetNamespace = "com.advantage.online.store.accountservice", partName = "GetAllAccountsRequest")
                    GetAllAccountsRequest getAllAccountsRequest);

    /**
     * @param addressUpdateRequest
     * @return returns accountservice.store.online.advantage.com.AddressUpdateResponse
     */
    @WebMethod(operationName = "AddressUpdate")
    @WebResult(name = "AddressUpdateResponse", targetNamespace = "com.advantage.online.store.accountservice", partName = "AddressUpdateResponse")
    public AddressUpdateResponse addressUpdate(
            @WebParam(name = "AddressUpdateRequest", targetNamespace = "com.advantage.online.store.accountservice", partName = "AddressUpdateRequest")
                    AddressUpdateRequest addressUpdateRequest);

    /**
     * @param getAddressesByAccountIdRequest
     * @return returns accountservice.store.online.advantage.com.GetAddressesByAccountIdResponse
     */
    @WebMethod(operationName = "GetAddressesByAccountId")
    @WebResult(name = "GetAddressesByAccountIdResponse", targetNamespace = "com.advantage.online.store.accountservice", partName = "GetAddressesByAccountIdResponse")
    public GetAddressesByAccountIdResponse getAddressesByAccountId(
            @WebParam(name = "GetAddressesByAccountIdRequest", targetNamespace = "com.advantage.online.store.accountservice", partName = "GetAddressesByAccountIdRequest")
                    GetAddressesByAccountIdRequest getAddressesByAccountIdRequest);

    /**
     * @param addMasterCreditMethodRequest
     * @return returns accountservice.store.online.advantage.com.AddMasterCreditMethodResponse
     */
    @WebMethod(operationName = "AddMasterCreditMethod")
    @WebResult(name = "AddMasterCreditMethodResponse", targetNamespace = "com.advantage.online.store.accountservice", partName = "AddMasterCreditMethodResponse")
    public AddMasterCreditMethodResponse addMasterCreditMethod(
            @WebParam(name = "AddMasterCreditMethodRequest", targetNamespace = "com.advantage.online.store.accountservice", partName = "AddMasterCreditMethodRequest")
                    AddMasterCreditMethodRequest addMasterCreditMethodRequest);

    /**
     * @param addSafePayMethodRequest
     * @return returns accountservice.store.online.advantage.com.AddSafePayMethodResponse
     */
    @WebMethod(operationName = "AddSafePayMethod")
    @WebResult(name = "AddSafePayMethodResponse", targetNamespace = "com.advantage.online.store.accountservice", partName = "AddSafePayMethodResponse")
    public AddSafePayMethodResponse addSafePayMethod(
            @WebParam(name = "AddSafePayMethodRequest", targetNamespace = "com.advantage.online.store.accountservice", partName = "AddSafePayMethodRequest")
                    AddSafePayMethodRequest addSafePayMethodRequest);

    /**
     * @param updateSafePayMethodRequest
     * @return returns accountservice.store.online.advantage.com.UpdateSafePayMethodResponse
     */
    @WebMethod(operationName = "UpdateSafePayMethod")
    @WebResult(name = "UpdateSafePayMethodResponse", targetNamespace = "com.advantage.online.store.accountservice", partName = "UpdateSafePayMethodResponse")
    public UpdateSafePayMethodResponse updateSafePayMethod(
            @WebParam(name = "UpdateSafePayMethodRequest", targetNamespace = "com.advantage.online.store.accountservice", partName = "UpdateSafePayMethodRequest")
                    UpdateSafePayMethodRequest updateSafePayMethodRequest);

    /**
     * @param countrySearchRequest
     * @return returns accountservice.store.online.advantage.com.CountrySearchResponse
     */
    @WebMethod(operationName = "CountrySearch")
    @WebResult(name = "CountrySearchResponse", targetNamespace = "com.advantage.online.store.accountservice", partName = "CountrySearchResponse")
    public CountrySearchResponse countrySearch(
            @WebParam(name = "CountrySearchRequest", targetNamespace = "com.advantage.online.store.accountservice", partName = "CountrySearchRequest")
                    CountrySearchRequest countrySearchRequest);

    /**
     * @param getAccountConfigurationRequest
     * @return returns accountservice.store.online.advantage.com.GetAccountConfigurationResponse
     */
    @WebMethod(operationName = "GetAccountConfiguration")
    @WebResult(name = "GetAccountConfigurationResponse", targetNamespace = "com.advantage.online.store.accountservice", partName = "GetAccountConfigurationResponse")
    public GetAccountConfigurationResponse getAccountConfiguration(
            @WebParam(name = "GetAccountConfigurationRequest", targetNamespace = "com.advantage.online.store.accountservice", partName = "GetAccountConfigurationRequest")
                    GetAccountConfigurationRequest getAccountConfigurationRequest);

    /**
     * @param countryCreateRequest
     * @return returns accountservice.store.online.advantage.com.CountryCreateResponse
     */
    @WebMethod(operationName = "CountryCreate")
    @WebResult(name = "CountryCreateResponse", targetNamespace = "com.advantage.online.store.accountservice", partName = "CountryCreateResponse")
    public CountryCreateResponse countryCreate(
            @WebParam(name = "CountryCreateRequest", targetNamespace = "com.advantage.online.store.accountservice", partName = "CountryCreateRequest")
                    CountryCreateRequest countryCreateRequest);

    /**
     * @param updateMasterCreditMethodRequest
     * @return returns accountservice.store.online.advantage.com.UpdateMasterCreditMethodResponse
     */
    @WebMethod(operationName = "UpdateMasterCreditMethod")
    @WebResult(name = "UpdateMasterCreditMethodResponse", targetNamespace = "com.advantage.online.store.accountservice", partName = "UpdateMasterCreditMethodResponse")
    public UpdateMasterCreditMethodResponse updateMasterCreditMethod(
            @WebParam(name = "UpdateMasterCreditMethodRequest", targetNamespace = "com.advantage.online.store.accountservice", partName = "UpdateMasterCreditMethodRequest")
                    UpdateMasterCreditMethodRequest updateMasterCreditMethodRequest);

    /**
     * @param accountCreateRequest
     * @return returns accountservice.store.online.advantage.com.AccountCreateResponse
     */
    @WebMethod(operationName = "AccountCreate")
    @WebResult(name = "AccountCreateResponse", targetNamespace = "com.advantage.online.store.accountservice", partName = "AccountCreateResponse")
    public AccountCreateResponse accountCreate(
            @WebParam(name = "AccountCreateRequest", targetNamespace = "com.advantage.online.store.accountservice", partName = "AccountCreateRequest")
                    AccountCreateRequest accountCreateRequest);

    /**
     * @param accountLogoutRequest
     * @return returns accountservice.store.online.advantage.com.AccountLogoutResponse
     */
    @WebMethod(operationName = "AccountLogout")
    @WebResult(name = "AccountLogoutResponse", targetNamespace = "com.advantage.online.store.accountservice", partName = "AccountLogoutResponse")
    public AccountLogoutResponse accountLogout(
            @WebParam(name = "AccountLogoutRequest", targetNamespace = "com.advantage.online.store.accountservice", partName = "AccountLogoutRequest")
                    AccountLogoutRequest accountLogoutRequest);

    /**
     * @param changePasswordRequest
     * @return returns accountservice.store.online.advantage.com.ChangePasswordResponse
     */
    @WebMethod(operationName = "ChangePassword")
    @WebResult(name = "ChangePasswordResponse", targetNamespace = "com.advantage.online.store.accountservice", partName = "ChangePasswordResponse")
    public ChangePasswordResponse changePassword(
            @WebParam(name = "ChangePasswordRequest", targetNamespace = "com.advantage.online.store.accountservice", partName = "ChangePasswordRequest")
                    ChangePasswordRequest changePasswordRequest);

    /**
     * @param accountLoginRequest
     * @return returns accountservice.store.online.advantage.com.AccountLoginResponse
     */
    @WebMethod(operationName = "AccountLogin")
    @WebResult(name = "AccountLoginResponse", targetNamespace = "com.advantage.online.store.accountservice", partName = "AccountLoginResponse")
    public AccountLoginResponse accountLogin(
            @WebParam(name = "AccountLoginRequest", targetNamespace = "com.advantage.online.store.accountservice", partName = "AccountLoginRequest")
                    AccountLoginRequest accountLoginRequest);

    /**
     * @param getCountriesRequest
     * @return returns accountservice.store.online.advantage.com.GetCountriesResponse
     */
    @WebMethod(operationName = "GetCountries")
    @WebResult(name = "GetCountriesResponse", targetNamespace = "com.advantage.online.store.accountservice", partName = "GetCountriesResponse")
    public GetCountriesResponse getCountries(
            @WebParam(name = "GetCountriesRequest", targetNamespace = "com.advantage.online.store.accountservice", partName = "GetCountriesRequest")
                    GetCountriesRequest getCountriesRequest);

    /**
     * @param deletePaymentPreferenceRequest
     * @return returns accountservice.store.online.advantage.com.DeletePaymentPreferenceResponse
     */
    @WebMethod(operationName = "DeletePaymentPreference")
    @WebResult(name = "DeletePaymentPreferenceResponse", targetNamespace = "com.advantage.online.store.accountservice", partName = "DeletePaymentPreferenceResponse")
    public DeletePaymentPreferenceResponse deletePaymentPreference(
            @WebParam(name = "DeletePaymentPreferenceRequest", targetNamespace = "com.advantage.online.store.accountservice", partName = "DeletePaymentPreferenceRequest")
                    DeletePaymentPreferenceRequest deletePaymentPreferenceRequest);

    /**
     * @param addAddressesRequest
     * @return returns accountservice.store.online.advantage.com.AddAddressesResponse
     */
    @WebMethod(operationName = "AddAddresses")
    @WebResult(name = "AddAddressesResponse", targetNamespace = "com.advantage.online.store.accountservice", partName = "AddAddressesResponse")
    public AddAddressesResponse addAddresses(
            @WebParam(name = "AddAddressesRequest", targetNamespace = "com.advantage.online.store.accountservice", partName = "AddAddressesRequest")
                    AddAddressesRequest addAddressesRequest);

    /**
     * @param getAccountByIdNewRequest
     * @return returns accountservice.store.online.advantage.com.GetAccountByIdNewResponse
     */
    @WebMethod(operationName = "GetAccountByIdNew")
    @WebResult(name = "GetAccountByIdNewResponse", targetNamespace = "com.advantage.online.store.accountservice", partName = "GetAccountByIdNewResponse")
    public GetAccountByIdNewResponse getAccountByIdNew(
            @WebParam(name = "GetAccountByIdNewRequest", targetNamespace = "com.advantage.online.store.accountservice", partName = "GetAccountByIdNewRequest")
                    GetAccountByIdNewRequest getAccountByIdNewRequest);

    /**
     * @param accountUpdateRequest
     * @return returns accountservice.store.online.advantage.com.AccountUpdateResponse
     */
    @WebMethod(operationName = "AccountUpdate")
    @WebResult(name = "AccountUpdateResponse", targetNamespace = "com.advantage.online.store.accountservice", partName = "AccountUpdateResponse")
    public AccountUpdateResponse accountUpdate(
            @WebParam(name = "AccountUpdateRequest", targetNamespace = "com.advantage.online.store.accountservice", partName = "AccountUpdateRequest")
                    AccountUpdateRequest accountUpdateRequest);

    /**
     * @param paymentMethodUpdateRequest
     * @return returns accountservice.store.online.advantage.com.PaymentMethodUpdateResponse
     */
    @WebMethod(operationName = "PaymentMethodUpdate")
    @WebResult(name = "PaymentMethodUpdateResponse", targetNamespace = "com.advantage.online.store.accountservice", partName = "PaymentMethodUpdateResponse")
    public PaymentMethodUpdateResponse paymentMethodUpdate(
            @WebParam(name = "PaymentMethodUpdateRequest", targetNamespace = "com.advantage.online.store.accountservice", partName = "PaymentMethodUpdateRequest")
                    PaymentMethodUpdateRequest paymentMethodUpdateRequest);

}
