server:
  port: 9999
spring:
  application:
     name: gateway
ribbon:
  eureka:
    enabled: false

logging:
  level:
    root: DEBUG
management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: gateway
zuul:
  routes:
    web:
      path: /**
    accountservice:
      path: /accountservice/**
      stripPrefix: false

  host:
    connect-timeout-millis: 15000
    socket-timeout-millis: 15000

web:
  ribbon:
    listOfServers: localhost:8080
    ConnectTimeout: 15000
    ReadTimeout: 15000
accountservice:
  ribbon:
    listOfServers: localhost:8080
    ConnectTimeout: 15000
    ReadTimeout: 15000