
package AccountServiceClient;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AccountServicePort", targetNamespace = "com.advantage.online.store.accountservice")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AccountServicePort {


    /**
     * 
     * @param getCountriesRequest
     * @return
     *     returns AccountServiceClient.GetCountriesResponse
     */
    @WebMethod(operationName = "GetCountries")
    @WebResult(name = "GetCountriesResponse", targetNamespace = "com.advantage.online.store.accountservice", partName = "GetCountriesResponse")
    public GetCountriesResponse getCountries(
        @WebParam(name = "GetCountriesRequest", targetNamespace = "com.advantage.online.store.accountservice", partName = "GetCountriesRequest")
        Object getCountriesRequest);

    /**
     * 
     * @param getAccountByIdRequest
     * @return
     *     returns AccountServiceClient.GetAccountByIdResponse
     */
    @WebMethod(operationName = "GetAccountById")
    @WebResult(name = "GetAccountByIdResponse", targetNamespace = "com.advantage.online.store.accountservice", partName = "GetAccountByIdResponse")
    public GetAccountByIdResponse getAccountById(
        @WebParam(name = "GetAccountByIdRequest", targetNamespace = "com.advantage.online.store.accountservice", partName = "GetAccountByIdRequest")
        GetAccountByIdRequest getAccountByIdRequest);

    /**
     * 
     * @param countryCreateRequest
     */
    @WebMethod(operationName = "CountryCreate")
    @Oneway
    public void countryCreate(
        @WebParam(name = "CountryCreateRequest", targetNamespace = "com.advantage.online.store.accountservice", partName = "CountryCreateRequest")
        CountryCreateRequest countryCreateRequest);

    /**
     * 
     * @param accountsRequest
     * @return
     *     returns AccountServiceClient.AccountsResponse
     */
    @WebMethod(operationName = "Accounts")
    @WebResult(name = "AccountsResponse", targetNamespace = "com.advantage.online.store.accountservice", partName = "AccountsResponse")
    public AccountsResponse accounts(
        @WebParam(name = "AccountsRequest", targetNamespace = "com.advantage.online.store.accountservice", partName = "AccountsRequest")
        Object accountsRequest);

    /**
     * 
     * @param accountCreateRequest
     */
    @WebMethod(operationName = "AccountCreate")
    @Oneway
    public void accountCreate(
        @WebParam(name = "AccountCreateRequest", targetNamespace = "com.advantage.online.store.accountservice", partName = "AccountCreateRequest")
        AccountCreateRequest accountCreateRequest);

    /**
     * 
     * @param accountUpdateRequest
     */
    @WebMethod(operationName = "AccountUpdate")
    @Oneway
    public void accountUpdate(
        @WebParam(name = "AccountUpdateRequest", targetNamespace = "com.advantage.online.store.accountservice", partName = "AccountUpdateRequest")
        AccountUpdateRequest accountUpdateRequest);

    /**
     * 
     * @param countrySearchRequest
     */
    @WebMethod(operationName = "CountrySearch")
    @Oneway
    public void countrySearch(
        @WebParam(name = "CountrySearchRequest", targetNamespace = "com.advantage.online.store.accountservice", partName = "CountrySearchRequest")
        CountrySearchRequest countrySearchRequest);

    /**
     * 
     * @param accountLoginRequest
     */
    @WebMethod(operationName = "AccountLogin")
    @Oneway
    public void accountLogin(
        @WebParam(name = "AccountLoginRequest", targetNamespace = "com.advantage.online.store.accountservice", partName = "AccountLoginRequest")
        AccountLoginRequest accountLoginRequest);

}
